
export const ENDPOINTS_API_PATH ={
    page: "page",
    authToken: "auth/token",
    authRefresh:"auth/refresh",
    airports_autocomplete: "airports/autocomplete",
    airports: "airports",
    route: "airline/route",
    user_preferences: "user/preferences",
    flight_search: 'flight/search',
    track: 'track',
    flight_trackHistory: 'flight/trackHistory',
    desolaAI: 'api/ask/',
    customerSignupPaymentRequest:'customer/signup',
    customerUpdatePaymentRequest: 'customer/update',
    paymentIntent:'payment/intent/create',
    subscriptionCreate:'subscription/create',
    confirmSubscription:'payment/intent/confirm',
    cancelSubscription:'subscription/cancel',
    stripe_getCustomer: 'customer',
    stripe_createCustomer: 'customer/signup',
    stripe_updateCustomer: 'customer/update',
    stripe_createPaymentIntent: 'subscription/paymentIntent/create',
    stripe_getPaymentIntent: 'subscription/paymentIntent',
    stripe_createSubscription: 'subscription/create-direct',
    stripe_cancelSubscription: 'subscription/cancel',
}