name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set Environment Variables
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> $GITHUB_ENV
          echo "VITE_API_TOKEN=${{ secrets.VITE_API_TOKEN }}" >> $GITHUB_ENV
          echo "VITE_B2C_TENANT=${{ secrets.VITE_B2C_TENANT }}" >> $GITHUB_ENV
          echo "VITE_B2C_CLIENT_ID=${{ secrets.VITE_B2C_CLIENT_ID }}" >> $GITHUB_ENV
          echo "VITE_B2C_AUTHORITY=${{ secrets.VITE_B2C_AUTHORITY }}" >> $GITHUB_ENV
          echo "VITE_B2C_SIGNUP_SIGNIN_POLICY=${{ secrets.VITE_B2C_SIGNUP_SIGNIN_POLICY }}" >> $GITHUB_ENV
          echo "VITE_B2C_PASSWORD_RESET_POLICY=${{ secrets.VITE_B2C_PASSWORD_RESET_POLICY }}" >> $GITHUB_ENV
          echo "VITE_B2C_REDIRECT_URI=${{ secrets.VITE_B2C_REDIRECT_URI }}" >> $GITHUB_ENV 
          echo "VITE_B2C_APPLICATION_SCOPE=${{ secrets.VITE_B2C_APPLICATION_SCOPE }}" >> $GITHUB_ENV 
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_ROCK_0A7BF3D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_ROCK_0A7BF3D10 }}
          action: "close"
          app_location: "/" # App source code path
